#github action to build, test and push SFC.Player application

name: Build, Test and Push SFC.Player Application

on:
  workflow_dispatch:  
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: 8.0.x 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Redis
        run: sudo apt-get install -y redis-tools redis-server

      - name: Verify Redis
        run: redis-cli ping

      - name: Dotnet restore dependencies
        run: dotnet restore SFC.Player.sln

      - name: Dotnet build
        run: dotnet build SFC.Player.sln --no-restore --configuration Release

      - name: Dotnet test
        run: dotnet test SFC.Player.sln --no-restore --no-build --configuration Release --verbosity normal /p:CollectCoverage=true /p:Threshold=0 /p:ThresholdStat=total
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build --tag ${{ secrets.DOCKER_ID }}/${{ vars.IMAGE_NAME }}:latest --build-arg BUILD_CONFIGURATION=Release --build-arg HTTP_PORT=7365 --build-arg HTTPS_PORT=7366 --file src/API/SFC.Player.Api/Dockerfile .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_ID }}/${{ vars.IMAGE_NAME }}:latest